# Generated by Django 4.2.17 on 2025-10-31 07:25

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("admin", "Admin")],
                        default="user",
                        max_length=10,
                    ),
                ),
                (
                    "plain_password",
                    models.CharField(
                        blank=True,
                        help_text="DEV ONLY - Insecure, for demo purposes only",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("last_login", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AdminSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight_education",
                    models.FloatField(
                        default=0.35,
                        help_text="Weight for education score",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "weight_skills",
                    models.FloatField(
                        default=0.45,
                        help_text="Weight for skills score",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "weight_experience",
                    models.FloatField(
                        default=0.2,
                        help_text="Weight for experience score",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "profession_zero_threshold",
                    models.FloatField(
                        default=0.2,
                        help_text="Below this: score = 0",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "profession_cap_threshold",
                    models.FloatField(
                        default=0.4,
                        help_text="Below this: cap score",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "partial_credit_cap",
                    models.FloatField(
                        default=30.0,
                        help_text="Score cap for transferable skills",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "allowed_degree_equivalences",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Degree mapping/equivalences",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Admin Settings",
                "verbose_name_plural": "Admin Settings",
            },
        ),
        migrations.CreateModel(
            name="JobDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("raw_text", models.TextField(help_text="Job description text")),
                (
                    "parsed_sections",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Parsed requirements, skills, etc.",
                    ),
                ),
                (
                    "requirements",
                    models.JSONField(
                        blank=True, default=list, help_text="Deduced requirements list"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_descriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("register", "Register"),
                            ("generate_resume", "Generate Resume"),
                            ("upload_resume", "Upload Resume"),
                            ("match", "Match Attempt"),
                            ("admin_update", "Admin Update"),
                            ("profile_update", "Profile Update"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Snapshot of action data"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="system_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[("uploaded", "Uploaded"), ("generated", "Generated")],
                        max_length=10,
                    ),
                ),
                (
                    "latex_source",
                    models.TextField(
                        blank=True, help_text="LaTeX source code", null=True
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="resumes/"),
                ),
                (
                    "parsed_text",
                    models.TextField(
                        blank=True, help_text="Extracted raw text", null=True
                    ),
                ),
                (
                    "parsed_sections",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Parsed education, skills, experience",
                    ),
                ),
                (
                    "latex_error",
                    models.TextField(
                        blank=True, help_text="LaTeX compilation errors", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="Professional summary/bio", null=True
                    ),
                ),
                (
                    "education_entries",
                    models.JSONField(
                        blank=True, default=list, help_text="List of education entries"
                    ),
                ),
                (
                    "skills",
                    models.JSONField(
                        blank=True, default=list, help_text="List of skills"
                    ),
                ),
                (
                    "experiences",
                    models.JSONField(
                        blank=True, default=list, help_text="List of work experiences"
                    ),
                ),
                (
                    "certifications",
                    models.JSONField(
                        blank=True, default=list, help_text="List of certifications"
                    ),
                ),
                (
                    "projects",
                    models.JSONField(
                        blank=True, default=list, help_text="List of projects"
                    ),
                ),
                (
                    "parsed_searchable_text",
                    models.TextField(
                        blank=True, help_text="Concatenated normalized text", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatchAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bert_scores",
                    models.JSONField(
                        default=dict,
                        help_text="BERT scores: education, skills, experience, final",
                    ),
                ),
                (
                    "gemini_correction",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Gemini validation and corrections",
                        null=True,
                    ),
                ),
                (
                    "final_score",
                    models.FloatField(
                        help_text="Final ATS score after corrections",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "breakdown_details",
                    models.JSONField(
                        default=dict, help_text="Matched/missing skills, gaps, etc."
                    ),
                ),
                (
                    "suggestion_text",
                    models.TextField(
                        blank=True,
                        help_text="Gemini improvement suggestions",
                        null=True,
                    ),
                ),
                (
                    "profession_match_flag",
                    models.BooleanField(
                        default=True, help_text="Whether profession matches"
                    ),
                ),
                (
                    "profession_similarity",
                    models.FloatField(
                        default=1.0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job_description",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="core.jobdescription",
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="core.resume",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
