# Generated by Django 4.2.17 on 2025-10-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="achievements",
            field=models.JSONField(
                blank=True, default=list, help_text="List of achievements and awards"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="city",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="github",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="profile",
            name="leadership",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of leadership or extracurricular roles",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="linkedin",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="profile",
            name="publications",
            field=models.JSONField(
                blank=True, default=list, help_text="List of publications"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="state",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
